name: "cross-tests"

inputs:
  rust:
    required: true
  package:
    required: true
  target:
    required: true
  features:
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust }}
          targets: ${{ inputs.target }}
      - uses: RustCrypto/actions/cross-install@master
      - if: ${{ inputs.features != 'NO_FEATURE' }}
        run: |
          cd ${{ inputs.package }}
          cross test --target ${{ inputs.target }} --no-default-features \
            --features ${{ inputs.features }}
        shell: bash
      - if: ${{ inputs.features == 'NO_FEATURE' }}
        run: |
          cd ${{ inputs.package }}
          cross test --target ${{ inputs.target }} --no-default-features
        shell: bash
