language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.0.0
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      script: ./build_nostd.sh
      install:
        - cargo install xargo --force
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src
  allow_failures:
    - rust: nightly
      before_script: rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --write-mode=diff
        - cd aesni ; cargo fmt -- --config-path ../rustfmt.toml --write-mode=diff

install:
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git japaric/cross --force
  - source ~/.cargo/env || true

script:
  - cross test --verbose --all --release --target $TARGET

cache: cargo
